import { Inter } from "next/font/google";
import "./globals.css";
import Header from '../components/Header';
import Providers from "./Providers";
import Footer from "@/components/Footer";
// import '../node_modules/bootstrap/dist/css/bootstrap.min.css'

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <script src="../path/to/flowbite/dist/flowbite.min.js"></script>
      </head>
      <body className={inter.className}>
      <Providers>
        <Header/>
        {children}
        <Footer />
      </Providers>
      </body>
    </html>
  );
}
